# Generated by Django 4.0.6 on 2023-02-16 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('studentId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('studentName', models.CharField(max_length=100)),
                ('contactNumber', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=100)),
                ('dateOfBirth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('birthPlace', models.CharField(max_length=100)),
                ('motherTongue', models.CharField(max_length=100)),
                ('cast', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('bloodGroup', models.CharField(max_length=100)),
                ('aadharNumber', models.IntegerField()),
                ('studentGroup', models.TextField()),
                ('extraActivities', models.TextField()),
                ('StudentImage', models.CharField(max_length=100)),
                ('Batch', models.TextField()),
                ('admissionDate', models.DateField()),
                ('siblingDetail', models.TextField()),
                ('Document', models.TextField()),
                ('admissionStatus', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='parentsDetail',
            fields=[
                ('parentsId', models.AutoField(primary_key=True, serialize=False)),
                ('parentsDetail', models.TextField()),
                ('Address', models.TextField()),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.studentdetail')),
            ],
        ),
    ]
