# Generated by Django 4.0.6 on 2023-02-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parentsdetail',
            old_name='parentsDetail',
            new_name='parentsDetailData',
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='admissionStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='bloodGroup',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('A+', 'A+'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='cast',
            field=models.CharField(choices=[('EWS', 'EWS'), ('General', 'General'), ('NT', 'NT'), ('OBC', 'OBC'), ('SBC', 'SBC'), ('SC', 'SC'), ('ST', 'ST'), ('VJ', 'VJ')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100),
        ),
    ]
